// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9QzyofSH7rquD0tfzRsuRxGNo5ppN28',
    appId: '1:692732084232:web:663231fde1e95b7f20d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    authDomain: 'authenticationapp-cb3ba.firebaseapp.com',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZ3y2_ypIl-_8idVO29GuvSoRbRua-bc',
    appId: '1:692732084232:android:f53dc4701b33205920d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsBY72uQ8cxHRctoj-JlbZ4rpDgx_mhu0',
    appId: '1:692732084232:ios:0f9f94eb8e77c2b620d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
    iosBundleId: 'com.example.authapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsBY72uQ8cxHRctoj-JlbZ4rpDgx_mhu0',
    appId: '1:692732084232:ios:0f9f94eb8e77c2b620d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
    iosBundleId: 'com.example.authapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE9QzyofSH7rquD0tfzRsuRxGNo5ppN28',
    appId: '1:692732084232:web:bf4300c64b8e162b20d1bd',
    messagingSenderId: '692732084232',
    projectId: 'authenticationapp-cb3ba',
    authDomain: 'authenticationapp-cb3ba.firebaseapp.com',
    storageBucket: 'authenticationapp-cb3ba.firebasestorage.app',
  );

}